version: '3'

services:
  db:
    build: ./db
    ports:
      - '5432:5432'
    environment: 
      POSTGRES_USER: "samuel"
      POSTGRES_DB_TEST: "samuel_test"
      POSTGRES_DB: "samuel_des" 
      POSTGRES_PASSWORD: "postgres"

  node-login:
      build: ./be
      command: npm run start
      depends_on: 
        - db
      links:
        - db
      ports:
          - "3001:3000"
