version: '3'

services:
    mysqlsrv:
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password
        environment:
          MYSQL_ROOT_PASSWORD: "MySql2019!"
          MYSQL_DATABASE: "testedb"
          MYSQL_USER: 'samuel'
          MYSQL_PASSWORD: 'MySql2019!'
          MYSQL_HOST: "%"
        ports:
          - "3306:3306"
        expose: 
          - 3306
        volumes:
          - ./db/mysql:/var/lib/mysql
        networks:
          - mysql-compose-network

    node-login:
        build: ./be
        command: npm run start
        ports:
            - "3000:3000"
        networks:
            - mysql-compose-network

networks: 
    mysql-compose-network:
        driver: bridge